name: Frontend Build

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: "ap-southeast-1"
  POSTS_CONTENT_BUCKET_NAME: "be-awesome-dev-posts"
  BUILD_ARTIFACT_BUCKET_NAME: "be-awesome-dev-build-artifact"

jobs:
  FrontEndBuild:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629872170007:role/BeAwesomeDevGithubActionWorkflowBuildPipeline
          role-session-name: github-action-role-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      # - name: Archive front-end build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: front-end-build-artifact
      #     path: ./front-end/out

  UploadBuildArtifactToS3:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::629872170007:role/BeAwesomeDevGithubActionWorkflowBuildPipeline
          role-session-name: github-action-role-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload build artifact to S3 bucket
        working-directory: ./front-end/out
        run: aws s3 cp . s3://${{ env.AWS_REGION }} --recursive
