name: Frontend Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  front-end-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Archive front-end build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: front-end-build-artifact
          path: ./front-end/out

      # - name: Deploy to hosting provider
      # Add your deployment step here
